# Copyright (c) 2025 Martin Pflaum
# This file is part of the diffinytrace project, licensed under the MIT License.
#%%
import os
import subprocess

# Step 1: Run sphinx-apidoc to generate .rst files
docs_dir = os.path.abspath(".")
source_dir = os.path.abspath("../diffinytrace")  # Path to the source directory
cmd = ['sphinx-apidoc']
cmd.append('-f')
# Add other necessary arguments to the command
cmd.append('-o')
cmd.append(docs_dir)  # Output directory
cmd.append(source_dir)  # Source directory

try:
    res = subprocess.run(cmd, text=True, capture_output=True, check=True)
    print(res)
    print(res.stdout)

except subprocess.CalledProcessError as e:
    print("CalledProcessError: " + str(e))
    print("Error Output: " + e.output)


import os
import re
# Directory containing the generated .rst files
rst_files_directory = r"."
# Read with specific encoding
#
index_basecontent = ""
with open('index_base.rst', 'r', encoding='utf-8') as file:
    index_basecontent += file.read()
with open('index_utilities.rst', 'r', encoding='utf-8') as file:
    index_basecontent += file.read()


# Process each .rst file generated by sphinx-apidoc
for rst_filename in os.listdir(rst_files_directory):
    # Check if the file starts with "diffinytrace." and ends with ".rst"
    cond = rst_filename.startswith("diffinytrace.") and rst_filename.endswith(".rst")
    cond = cond or (rst_filename.startswith("index_utilities.") and rst_filename.endswith(".rst"))
    cond = cond or (rst_filename.startswith("index_base.") and rst_filename.endswith(".rst"))
    cond = cond or (rst_filename.startswith("examples.") and rst_filename.endswith(".rst"))
    cond = cond or (rst_filename.split(".")[0] in index_basecontent and rst_filename.endswith(".rst"))
    
    
    if cond:
        print(f"Processing file: {rst_filename}")
        rst_file_path = os.path.join(rst_files_directory, rst_filename)
        
        # Read the file contents
        with open(rst_file_path, "r", encoding="utf-8") as rst_file:
            rst_content = rst_file.read()
        
        # Replace "diffinytrace.module_name package" with just "module_name"
        rst_content = re.sub(
            r"diffinytrace\.(\w+) package\n=+",
            lambda match: f"{match.group(1)}\n{'=' * len(match.group(1))}",
            rst_content
        )
        
        # Remove "diffinytrace." prefix from module references
        rst_content = re.sub(
            r"^diffinytrace.",  # Matches lines starting with "diffinytrace."
            "",                 # Replaces them with an empty string
            rst_content,
            flags=re.MULTILINE  # Enables multi-line matching
        )

        # Remove " module" and " package" suffixes from titles
        rst_content = re.sub(r" module", r"", rst_content)
        rst_content = re.sub(r" package", r"", rst_content)
        
        # Remove "Subpackages" section heading but keep the toctree
        rst_content = re.sub(
            r"Subpackages\n-+\n\n(.. toctree::.*?)(\n\n|$)",
            r"\1\n\n",
            rst_content,
            flags=re.DOTALL
        )
        
        # Remove "Submodules" section heading
        rst_content = re.sub(
            r"Submodules\n-+\n\n",
            "",
            rst_content
        )
        
        # Handle underscores in titles - temporarily replace them
        rst_content = re.sub(
            r"^(.*\_.*(?:\..+)*)\n(=+|-+)$",
            lambda match: f"{match.group(1).replace(r'\_', 'temreplace')}\n{match.group(2)}",
            rst_content,
            flags=re.MULTILINE
        )
        rst_content = re.sub(
            r"^(.*_.*(?:\..+)*)\n(=+|-+)$",
            lambda match: f"{match.group(1).replace(r'_', 'temreplace')}\n{match.group(2)}",
            rst_content,
            flags=re.MULTILINE
        )
        
        # Simplify module titles by using only the last part of dotted names
        rst_content = re.sub(
            r"^(\w+\.\w+(?:\.\w+)*)\n(=+|-+)$",
            lambda match: f"{match.group(1).split('.')[-1]}\n{match.group(2)}",
            rst_content,
            flags=re.MULTILINE
        )
        # Restore underscores as spaces
        rst_content = rst_content.replace("temreplace", " ")
        rst_content = re.sub(    
            r"^(.*)\n(=+|-+)$",
            lambda match: f"{match.group(1).title()}\n{match.group(2)}",
            rst_content,
            flags=re.MULTILINE
        )
        
        # Remove "Module contents" section at the end
        rst_content = re.sub(
            r"Module contents\n-+\n\n\.\. automodule:: .*?\n   :members:\n   :undoc-members:\n   :show-inheritance:\n",
            "",
            rst_content,
            flags=re.DOTALL
        )
        
        # Write the updated content back to the file
        with open(rst_file_path, "w", encoding="utf-8") as updated_rst_file:
            updated_rst_file.write(rst_content)


project = 'DiffinyTrace'
copyright = '2025, Martin Pflaum'
author = 'Martin Pflaum'
release = '2.1'
html_title = 'DiffinyTrace Documentation'
html_short_title = 'DiffinyTrace'

import os
import sys
import os
os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"
#sys.path.insert(0, os.path.abspath("."))
#sys.path.insert(0, os.path.abspath("../../diffinytrace"))
sys.path.insert(0, os.path.abspath(".."))
import shutil
import os

source_dir = "../examples"
target_dir = "."  # Change this to your target path

os.makedirs(target_dir, exist_ok=True)
def create_examples_rst(examples, output_file="examples.rst"):
    """
    Creates an examples.rst file from a list of example names.
    
    Args:
        examples (list): List of example names (strings).
        output_file (str): Path to the output file. Defaults to "examples.rst".
    """
    with open(output_file, 'w') as f:
        # Write the header
        f.write("Examples\n")
        f.write("=" * len("examples") + "\n\n")
        
        # Write the toctree directive
        f.write(".. toctree::\n")
        
        # Write each example name with proper indentation
        for example in examples:
            f.write(f"    {example}\n")

examples = []
for filename in os.listdir(source_dir):
    if filename.endswith(".ipynb"):
        full_src_path = os.path.join(source_dir, filename)
        full_dst_path = os.path.join(target_dir, filename)
        shutil.copy(full_src_path, full_dst_path)
        examples.append(filename.split(".")[0])  # Store the filename without extension

create_examples_rst(examples)
# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = ["sphinx.ext.autodoc",
              "sphinx.ext.autosummary",
              "sphinx.ext.napoleon",
              "sphinx.ext.viewcode",
              "sphinx.ext.mathjax",
            'sphinxcontrib.bibtex',
            "nbsphinx",
            "sphinx.ext.intersphinx"]

"""
extensions = [
#    "sphinx.ext.apidoc",             # Generate API documentation from Python packages
 #   "sphinx.ext.autodoc",            # Include documentation from docstrings
#    "sphinx.ext.autosectionlabel",   # Allow referencing sections by their title
    "sphinx.ext.autosummary",        # Generate autodoc summaries
#    "sphinx.ext.coverage",           # Collect doc coverage stats
    #"sphinx.ext.doctest",            # Test snippets in the documentation
    #"sphinx.ext.duration",           # Measure durations of Sphinx processing
    #"sphinx.ext.extlinks",           # Markup to shorten external links
    #"sphinx.ext.githubpages",        # Publish HTML docs in GitHub Pages
    #"sphinx.ext.graphviz",           # Add Graphviz graphs
    #"sphinx.ext.ifconfig",           # Include content based on configuration
    #"sphinx.ext.imgconverter",       # A reference image converter using ImageMagick
    #"sphinx.ext.inheritance_diagram",# Include inheritance diagrams
    "sphinx.ext.intersphinx",        # Link to other projects’ documentation
#    "sphinx.ext.linkcode",           # Add external links to source code
    "sphinx.ext.mathjax",            # Math support for HTML outputs in Sphinx
    "sphinx.ext.napoleon",           # Support for NumPy and Google style docstrings
    #"sphinx.ext.todo",               # Support for todo items
    "sphinx.ext.viewcode",           # Add links to highlighted source code
    "sphinx_rtd_theme"]"""

templates_path = ['_templates']
exclude_patterns = []

autosummary_generate = True
autodoc_member_order = 'bysource'


# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

#html_theme = 'sphinx_rtd_theme'
html_theme = "furo"
html_static_path = ['_static']
html_theme_options = {
    "light_logo": "logo_light.svg",
    "dark_logo": "logo_dark.svg",
    "sidebar_hide_name": True,
}

bibtex_bibfiles = ['refs.bib']

mathjax3_config = {
    'tex': {
        #'macros': {
        #    'R': '\\mathbb{R}'
        #}
    }
}
nbsphinx_allow_errors = True
nbsphinx_execute = 'never'


# Exclude certain notebooks from processing
nbsphinx_execute_arguments = [
    "--InlineBackend.figure_formats={'svg', 'pdf'}",
    "--InlineBackend.rc={'figure.dpi': 96}",
]
